Vagrant.configure(2) do |config|
	#config.vm.define "ubuntu" do |ctl|
	#	ctl.vm.box = "ubuntu/trusty64"
	#	ctl.vm.hostname = "ubuntu-control"
	#	#ctl.vm.network "private_network", ip: "192.168.57.2"
	#	ctl.vm.provider "virtualbox" do |vb|
	#		vb.memory = 1024
	#	end
	#end
	config.vm.define "macos" do |macos|
		macos.vm.box = "mcandre/vagrant-macos-xcode"
		macos.vm.box_version = "0.0.1"
		macos.vm.hostname = "macos-server"
		macos.disksize.size = '100GB'
		macos.vm.network "private_network", ip: "192.168.100.2"
		macos.vm.provider "virtualbox" do |vb|
			vb.memory = 1024
		end
	end
	config.vm.define "windows" do |windows|
		windows.vm.box = "promet/windows2012"
		windows.vm.box_version = "1.1"
		windows.vm.hostname = "windows-server"
		windows.disksize.size = '80GB'
		windows.vm.communicator = "winrm"
		windows.winrm.username = "vagrant"
		windows.winrm.password = "vagrant"
		windows.vm.synced_folder ".", "/vagrant", disabled: true
		windows.vm.network "private_network", ip: "192.168.100.3"
		windows.vm.provider "virtualbox" do |vb|
			vb.memory = 2048
			vb.cpus = 2
		end
	end
end
